---
- name: remove deprecated packages
  ansible.builtin.apt:
    name: [containerd, docker, docker-engine, docker.io, runc]
    state: absent

- name: ensure apt over http requirements
  ansible.builtin.apt:
    name: [apt-transport-https, ca-certificates, gnupg]
    install_recommends: false
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"

- name: ensure docker engine apt key
  ansible.builtin.apt_key:
    url: "{{ docker_apt_repository.key_url | default(omit) }}"
    keyserver: "{{ docker_apt_repository.key_server | default(omit) }}"
    id: "{{ docker_apt_repository.key_id | default(omit) }}"

- name: ensure docker engine apt repository
  ansible.builtin.apt_repository:
    filename: docker
    repo: "deb [arch=amd64] {{ docker_apt_repository.repo_url }} {{ ansible_distribution_release }} {{ docker_apt_repository.repo_branch | default('stable') }}"

- name: ensure docker engine
  ansible.builtin.apt:
    name: [containerd.io, docker-ce, docker-ce-cli, python3-docker, python3-six]
    install_recommends: false
    update_cache: true
    cache_valid_time: "{{ '1d' | community.general.to_seconds | int }}"
